// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    public partial class Armies
    {
        public Armies()
        {
            ContentsOfArmies = new HashSet<ContentsOfArmies>();
        }

        [Key]
        [Column("army_name")]
        [StringLength(50)]
        public string ArmyName { get; set; }
        [Required]
        [Column("path_to_icon")]
        [StringLength(200)]
        public string PathToIcon { get; set; }

        [InverseProperty("ArmyNameNavigation")]
        public virtual ContentsOfArmyGroups ContentsOfArmyGroups { get; set; }
        [InverseProperty("ArmyNameNavigation")]
        public virtual ICollection<ContentsOfArmies> ContentsOfArmies { get; set; }
    }
}