// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    [Table("Army groups")]
    public partial class ArmyGroups
    {
        public ArmyGroups()
        {
            ContentsOfArmyGroups = new HashSet<ContentsOfArmyGroups>();
        }

        [Key]
        [Column("army_group_name")]
        [StringLength(50)]
        public string ArmyGroupName { get; set; }
        [Required]
        [Column("path_to_icon")]
        [StringLength(200)]
        public string PathToIcon { get; set; }

        [InverseProperty("ArmyGroupNavigation")]
        public virtual ICollection<ContentsOfArmyGroups> ContentsOfArmyGroups { get; set; }
    }
}