// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    [Table("Contents of divisions")]
    public partial class ContentsOfDivisions
    {
        [Key]
        [Column("line")]
        public int Line { get; set; }
        [Required]
        [Column("division_name")]
        [StringLength(50)]
        public string DivisionName { get; set; }
        [Required]
        [Column("battalion_name")]
        [StringLength(50)]
        public string BattalionName { get; set; }
        [Column("battalion_count")]
        public byte BattalionCount { get; set; }

        [ForeignKey("BattalionName")]
        [InverseProperty("ContentsOfDivisions")]
        public virtual Battalions BattalionNameNavigation { get; set; }
        [ForeignKey("DivisionName")]
        [InverseProperty("ContentsOfDivisions")]
        public virtual Divisions DivisionNameNavigation { get; set; }
    }
}