// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    public partial class Divisions
    {
        public Divisions()
        {
            ContentsOfArmies = new HashSet<ContentsOfArmies>();
            ContentsOfDivisions = new HashSet<ContentsOfDivisions>();
        }

        [Key]
        [Column("division_name")]
        [StringLength(50)]
        public string DivisionName { get; set; }
        [Column("path_to_icon")]
        [StringLength(200)]
        public string PathToIcon { get; set; }

        [InverseProperty("DivisionNameNavigation")]
        public virtual ICollection<ContentsOfArmies> ContentsOfArmies { get; set; }
        [InverseProperty("DivisionNameNavigation")]
        public virtual ICollection<ContentsOfDivisions> ContentsOfDivisions { get; set; }
    }
}