// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    public partial class Generals
    {
        [Key]
        [Column("general_name")]
        [StringLength(50)]
        public string GeneralName { get; set; }
        [Column("attack_bonus")]
        public float AttackBonus { get; set; }
        [Column("defense_bonus")]
        public float DefenseBonus { get; set; }
        [Required]
        [Column("path_to_icon")]
        [StringLength(200)]
        public string PathToIcon { get; set; }
        [Required]
        [Column("rank")]
        [StringLength(20)]
        public string Rank { get; set; }
        [Required]
        [Column("country")]
        [StringLength(3)]
        public string Country { get; set; }

        [ForeignKey("Country")]
        [InverseProperty("Generals")]
        public virtual Countries CountryNavigation { get; set; }
    }
}