// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    public partial class Modifiers : INotifyPropertyChanged
    {
        #region INPC
        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string name = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }
        #endregion

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("battalion_type")]
        [StringLength(3)]
        [Unicode(false)]
        public string BattalionType { get; set; }
        [Column("property")]
        [StringLength(50)]
        public string Property { get; set; }
        [Column("modifier")]
        public float? Modifier { get; set; }
        [Column("path_to_icon")]
        [StringLength(200)]
        public string PathToIcon { get; set; }

        public void UpdateProperties()
        {
            OnPropertyChanged(nameof(Id));
            OnPropertyChanged(nameof(Name));
            OnPropertyChanged(nameof(PathToIcon));
            OnPropertyChanged(nameof(BattalionType));
            OnPropertyChanged(nameof(Property));
            OnPropertyChanged(nameof(Modifier));
        }
    }
}