// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    [Table("Paths to Division icons")]
    public partial class PathsToDivisionIcons
    {
        [Key]
        [Column("path")]
        [StringLength(100)]
        public string Path { get; set; }
    }
}