// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    [Keyless]
    [Table("Paths to Modifiers icons")]
    public partial class PathsToModifiersIcons
    {
        [Column("path")]
        public string Path { get; set; }
    }
}