// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExtremeIroningTool.Utilitary_classes.DataBaseClasses
{
    [Table("Unit-specific Attack Adjusters")]
    public partial class UnitSpecificAttackAdjusters
    {
        [Key]
        [Column("battalion_name")]
        [StringLength(50)]
        public string BattalionName { get; set; }
        [Column("forest")]
        public float? Forest { get; set; }
        [Column("hill")]
        public float? Hill { get; set; }
        [Column("mountains")]
        public float? Mountains { get; set; }
        [Column("plains")]
        public float? Plains { get; set; }
        [Column("urban")]
        public float? Urban { get; set; }
        [Column("jungle")]
        public float? Jungle { get; set; }
        [Column("marsh")]
        public float? Marsh { get; set; }
        [Column("desert")]
        public float? Desert { get; set; }
        [Column("river")]
        public float? River { get; set; }
        [Column("amphibious")]
        public float? Amphibious { get; set; }
        [Column("fort")]
        public float? Fort { get; set; }

        [ForeignKey("BattalionName")]
        [InverseProperty("UnitSpecificAttackAdjusters")]
        public virtual Battalions BattalionNameNavigation { get; set; }
    }
}